themes/wdfn_theme/package-lock.json, themes/wdfn_theme/package.json
Update Dependencies
-----------
An across the board update of dependencies. Used NPM update and install commands to do the actual work. Ran docker-compose up to activate a local Hugo server and visually inspected the results. The running application looked and functioned as expected.
=> Update dependencies 5 9 19

Jenkinsfile, buildDeploy.sh
S3 Bucket Name Change
-----------
Changes to code so that the Jenkins job will deliver the Hugo website to the correct bucket on S3
Description
-----------
Shawn Noble was tasked with creating a URL to access the 'waterdata' landing page stored in an Amazon Web Service S3 bucket. In this process he offered to create new buckets via cloud template. He also changed the bucket names to better match Engineering Branch standards. Because of this name change the Jenkinsfile and related logic need to change as well.
=> S3 bucket name change

buildDeploy.sh
=> Corrected environment variable name

buildDeploy.sh
Title
-----------
Description
-----------
=> Fixed typo

Dockerfile, docker-compose.yml
=> Removed the "as hugo_base". This may be causing issues with the deploy

themes/wdfn_theme/layouts/partials/header.html, themes/wdfn_theme/package-lock.json
=> IOW-21 Fixed the flag icon and extra slash in about link

content/connector.md
Title
-----------
Description
-----------
=> remove comma

content/connector.md, content/nldi.md, layouts/index.html
Title
-----------
Description
-----------
=> update a date and the index page

Dockerfile, Jenkinsfile, awsTierDeploy.sh, content/connector.md, content/graph-images.md
Title
-----------
Description
-----------
=> harden deployment procedures

Dockerfile
Title
-----------
Description
-----------
=> update dockerfile to install npm

Dockerfile
Title
-----------
Description
-----------
=> update node source version

Dockerfile
Title
-----------
Description
-----------
=> remove npm installation

content/nldi.md
Title
-----------
Description
-----------
=> slide back NLDI for a moment

CHANGELOG.md, content/nldi.md
Title
-----------
Description
-----------
=> changelog, nldi

content/nldi.md
Title
-----------
dropping NLDI content from visible 
Description
-----------
=> push nldi to future

CHANGELOG.md, README.md, themes/wdfn_theme/package-lock.json, themes/wdfn_theme/package.json
=> Update dependencies include wdfn-viz (1.5.0)

Dockerfile, themes/wdfn_theme/package-lock.json, themes/wdfn_theme/package.json, themes/wdfn_theme/rollup.config.js
…Dockerfile to use python 3.8 and the latest version of Hugo 0.69.0
I have tested both on my local environment and using the docker-compose commands.
=> Updated dependencies and removed unused dependencies and updated the

CHANGELOG.md, content/graph-images.md
=> Updated graph server description with info and links to openAPI docs.

Jenkinsfile
Title
-----------
Description
-----------
=> use the right worker

data/roadmap/roadmap.yaml
Title
-----------
Description
-----------
=> more roadmap changes

data/roadmap/roadmap.yaml
Title
-----------
Description
-----------
=> Tiny edit on NWIS survey

content/roadmap/_index.md, data/roadmap/roadmap.yaml, layouts/section/roadmap.html
Title
-----------
Description
-----------
=> refine roadmap

content/roadmap/_index.md
Title
-----------
Description
-----------
=> Removed extra "of"

content/graph-images.md, layouts/index.html
Title
-----------
Description
-----------
=> update nldi date

content/roadmap/_index.md, data/roadmap/roadmap.yaml, layouts/section/roadmap.html
Title
-----------
Description
-----------
=> reorder YAML

data/roadmap/roadmap.yaml
Title
-----------
Description
-----------
=> more data services content

content/roadmap/_index.md, data/roadmap/roadmap.yaml, themes/wdfn_theme/layouts/partials/header.html
Title
-----------
Description
-----------
=> Add a link

content/nldi.md
related to: https://github.com/ACWI-SSWD/nldi-services/issues/53
Title
-----------
Description
-----------
=> add WGS 84 to documentation

themes/wdfn_theme/layouts/partials/header.html, themes/wdfn_theme/package-lock.json, themes/wdfn_theme/package.json
Title
-----------
Description
-----------
=> Updated dependencies and gov banner guidance

themes/wdfn_theme/package-lock.json, themes/wdfn_theme/package.json
Title
-----------
Description
-----------
=> Updated dependencies

themes/wdfn_theme/layouts/partials/footer.html
Title
-----------
Description
-----------
=> Fixed sprite reference URL

content/graph-images.md
Title
-----------
Description
-----------
=> Update some typos

awsTierDeploy.sh
Change to AWS Deploy
-----------
We don't want to delete the 'lookup' files that are stored in the labs-test bucket so this adds an exclude to prevent that from happening. 
=> change to aws deploy

.gitignore, Dockerfile, content/sensorthings.md, frontmatter.json, themes/wdfn_theme/src/styles/main.scss
Title
-----------
Description
-----------
=> got the build working, added some sensorthings content

Dockerfile
Title
-----------
update roadmap
Description
-----------
updated roadmap and a first pass at more sensorthings documentation
=> add awscli

Dockerfile, themes/wdfn_theme/package-lock.json, themes/wdfn_theme/package.json
Title
-----------
Description
-----------
=> Dependency update and use node version 16 in docker file

CHANGELOG.md, data/roadmap/roadmap.yaml, layouts/index.html
Description
-----------
Updated roadmap and remove old tile at index.
=> Updates to roadmap and index page

themes/wdfn_theme/layouts/partials/footer.html, themes/wdfn_theme/package-lock.json, themes/wdfn_theme/package.json
Title
-----------
Description
-----------
=> update footer and dependencies

themes/wdfn_theme/layouts/partials/header.html, themes/wdfn_theme/package-lock.json, themes/wdfn_theme/package.json
Title
-----------
Description
-----------
=> Update to wdfn-viz 3.0.1

CHANGELOG.md, data/roadmap/roadmap.yaml, layouts/section/roadmap.html
Title
-----------
Update roadmap page for NHGF
Description
-----------
Small text changes to the NHGF content on the roadmap page.  The largest change is an if statement in the roadmap.html Hugo template that checks if a top-level status exists as one of the content changes asks was to remove that.
=> Update roadmap page for NHGF

themes/wdfn_theme/package-lock.json, themes/wdfn_theme/package.json, themes/wdfn_theme/src/styles/main.scss
Title
-----------
Description
-----------
=> Updated to use wdfnviz 3.2.0
